version: '3.7'

services:
  front:
    container_name: contabil_front
    hostname: contabil_front
    build:
      context: ./contabil-web-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "18000:80"
    expose:
      - 18000
  
  back:
    container_name: contabil_back
    hostname: contabil_back
    build:
      context: ./contabil
      dockerfile: Dockerfile
    restart: always
    ports:
      - "18080:8080"
    expose:
      - 18080
  
