

services:
  db:
    container_name: Database_contabil
    hostname: Database_contabil
    image: postgres:alpine
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: contabil
      POSTGRES_HOST: 0.0.0.0
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
  
  front:
    container_name: contabil_front
    hostname: contabil_front
    build:
      context: ./contabil-web-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"
    expose:
      - 4200
    

  
  adminer: # interface para o banco de dados
    image: adminer
    restart: always
    ports:
      - 8000:8080
    links:
      - db
  
volumes: # volume para persistir os dados do banco de dados
  postgres-db:
